### ISSUE TITLE
Cache linksharing ZIP file "central directory" size

### ISSUE THREAD

**Issue by wthorp** [storj/gateway-mt#108] opened 2021-11-24 12:07 UTC
The "central directory" of a ZIP file is stored at the end of the file.  We could request a chunk of data from the end of an archive and hope this is sufficient, or we could persist the size "central directory".  Determine where this information might best be cached, and implement this caching strategy.

One option is to cache info in satellite metadata.  Another is to preserve this index in the linksharing cache when evicting a "central directory" cache record.

**Comment by ferristocrat** [comment] 2022-04-28 19:47
Move this to new milestone :)

**Comment by amwolff** [comment] 2023-09-28 16:54
is it a duplicate of #107?

**Comment by ferristocrat** [comment] 2023-10-24 00:02
Duplicate of #107

**Closed by ferristocrat** 2023-10-24 00:02 UTC
Labels: linksharing, edge
