### ISSUE TITLE
Investigate new interfaces for tooling

### ISSUE THREAD

**Issue by wthorp** [storj/gateway-mt#109] opened 2021-11-24 14:22 UTC
There are tasks of interacting with the auth service database that are outside of the Key Value Store scope.  This include administrative tasks such as manually disabling a specific key, as well synchronization and backup tasks if we assume that the underlying database doesn't have built-in consistency features.

We want to be able to run these tasks independent of the underlying data store technology; EG: CQL vs KV vs SQL, or CRDB vs Cassandra.  We need an interface that our tools can interact with to accomplish this.  In many of these cases, certain features will already be implemented by the underlying database and their concrete implementations will be no-ops.

Implement these interfaces for part of this ticket for custom auth and in-memory KV store.

**Comment by shaupt131** [comment] 2022-03-28 13:35
Currently, admin can connect to auth service DB directly and modify the data if required (takedown request, etc).  With the new auth database, we don't have this ability.

**Comment by halkyon** [comment] 2022-04-27 04:57
Speaking of the caches, we'll most likely be removing the authclient cache since badgerauth is lightweight and accesses are fast, so it doesn't seem to be necessary. Minio also has a cache (global IAM users map), so this would need to be dealt with too. There's a todo here already: https://github.com/storj/gateway-mt/blob/main/pkg/minio/iam-storj-store.go#L79

**Comment by halkyon** [comment] 2022-04-29 06:54
Some thoughts here, after feedback. It seems like a CLI tool would be the best option, at least for the moment. Allowing it someone to follow some instructions to run it (thinking of people on-call here), and making it easy to extend seem like good goals here. Some high level points to consider:

* Separate tool, not part of the authservice itself, but it connects to authservice. Probably can be in the gateway-mt repo, but allow it to be independently built and run of the server.
* Combine existing tools into this new tool, e.g. [authservice-lookup-util](https://github.com/storj/gateway-mt/blob/main/cmd/authservice-lookup-util/main.go), and [authservice-unused-records](https://github.com/storj/gateway-mt/tree/main/cmd/authservice-unused-records)
* Backup is handled separately.
* Updates to the CLI tool probably shouldn't require a change on the server to add more endpoints to support it, if we can help it. There's obviously exceptions here, but I'm thinking of the scenario where we need to add a task quickly on-call, and having to get review for the change, and doing a release and deploy wouldn't be ideal.
* This tool needs to communicate with all nodes in the badgerauth cluster when performing a task. Badgerauth nodes only replicate records when a user puts a record at the KV interface, and that was a design decision of the new database. There are some records that are node specific though, such as the clock and replication log entries. For the client to connect, this could just mean passing all the node addresss to the nodes argument of the tool (or storing them in a config file), or if you connect to a single authservice, it could proxy your change to the other nodes for you (the latter is a random thought, but I'm not sure it's a good idea?)
  * I'm not sure if we need it to support every backend, like the original issue proposes. Most of the big gap in tooling comes from badgerauth specifically due to it not having a backend way of managing records.
    * We haven't confirmed what we're doing with the other backends once we've rolled out badgerauth


I started something in https://review.dev.storj.io/c/storj/gateway-mt/+/7365, but I had some struggles with this, especially around working with the data types. think we'd be better off making a DRPC server and connect the client that way.

**Comment by halkyon** [comment] 2022-05-09 18:50
Closing this out, will create issues for implementation

**Closed by halkyon** 2022-05-09 18:50 UTC
Labels: authservice
