### ISSUE TITLE
Ability to query info about an access_key

### ISSUE THREAD

**Issue by wthorp** [storj/gateway-mt#170] opened 2022-03-09 18:45 UTC
We have the situation where users may have an access grant that's not working, but they don't know why.  It would be nice to easily query about the satellite and caveats attached to an access_key.

**Comment by amwolff** [comment] 2022-03-09 18:47
Possible duplicate of #126

**Comment by wthorp** [comment] 2022-03-09 18:47
Jennifer @ Storj asked for this.

**Comment by wthorp** [comment] 2022-03-09 18:49
yep, dupe

**Closed** 2022-03-09 18:49 UTC
Labels: authservice
