### ISSUE TITLE
Increase timeouts in linksharing/CertMagic when used with GCS

### ISSUE THREAD

**Issue by amwolff** [storj/gateway-mt#287] opened 2023-01-10 15:19 UTC
## Expected Behavior

Using storj.io/gateway-mt/pkg/certstorage with GCS and multi-regional buckets shouldn't timeout on locking operations.

## Current Behavior

`certstorage: gcslock: unexpected response: gcsops: Delete "...": context deadline exceeded`

## Possible Solution

In my testing, things worked correctly, but I used a single-region bucket. Locking/unlocking is very expensive in terms of roundtrips, so what happens for multi-regional buckets probably cannot be avoided. Let's increase timeouts, but first, find where to do that in CertMagic. In `pkg/certstorage` and child packages, there are no hard timeouts.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by halkyon** [comment] 2023-01-30 05:43
It seems like this might be timing out at https://github.com/caddyserver/certmagic/blob/c0dc63288aceb406d9bd665fb739da38cdc1a773/handshake.go#L474. I'm not able to reproduce the issue again, though.

When I was initially setting things up, I had forgotten a CAA record that meant it tried GA CA first and failed, then failed over to Let's Encrypt. That was also on the non-staging issuer. I couldn't get the staging issuer to fail with a missing CAA record.

```
linksharing-linksharing-1  | 2023-01-05T16:06:39.476Z	ERROR	obtain	unable to unlock	{"identifier": "...", "lock_key": "...", "error": "certstorage: gcslock: unexpected response: gcsops: Delete "...": context deadline exceeded", "errorVerbose": "certstorage: gcslock: unexpected response: gcsops: Delete "...": context deadline exceeded\n\tstorj.io/gateway-mt/pkg/gcslock.(*Mutex).Unlock:105\n\tstorj.io/gateway-mt/pkg/certstorage.(*GCS).Unlock:93\n\tgithub.com/caddyserver/certmagic.releaseLock:262\n\tgithub.com/caddyserver/certmagic.(*Config).obtainCert.func1:494\n\tgithub.com/caddyserver/certmagic.(*Config).obtainCert:614\n\tgithub.com/caddyserver/certmagic.(*Config).ObtainCertAsync:462\n\tgithub.com/caddyserver/certmagic.(*Config).obtainOnDemandCertificate:447\n\tgithub.com/caddyserver/certmagic.(*Config).getCertDuringHandshake:314\n\tgithub.com/caddyserver/certmagic.(*Config).GetCertificate:77\n\tcrypto/tls.(*Config).getCertificate:1064\n\tcrypto/tls.(*serverHandshakeStateTLS13).pickCertificate:363\n\tcrypto/tls.(*serverHandshakeStateTLS13).handshake:55\n\tcrypto/tls.(*Conn).serverHandshake:54\n\tcrypto/tls.(*Conn).handshakeContext:1460\n\tcrypto/tls.(*Conn).HandshakeContext:1403\n\tnet/http.(*conn).serve:1848"}

**Comment by halkyon** [comment] 2023-01-31 00:51
Can't replicate this, tried to create and renew certificates including some mistakes in the DNS to see if that causes some kind of timeout with the issuers. We do have `__GCS__Lock` and `__GCS__Unlock` function metrics we can keep an eye on to make sure there's not too much latency in doing various operations with the storage. From my testing I did not see any significant slowness, even after creating a many number of certs. Note that lock objects expire after 5 minutes, so there's nothing left laying around indefinitely if a timeout occurs and locks did not get cleaned up.

I'll close this for now. Let's reopen if the issue comes up again.

**Closed by halkyon** 2023-01-31 00:51 UTC
Labels: bug, linksharing, Needs Investigation, edge
